/*
  # Initial Schema Setup for FS-Store

  ## Query Description:
  This migration sets up the core e-commerce tables: products, cart_items, orders, and order_items.
  It also seeds the products table with initial high-quality data.

  ## Metadata:
  - Schema-Category: Structural
  - Impact-Level: High
  - Requires-Backup: false
  - Reversible: true

  ## Structure Details:
  - Tables: products, cart_items, orders, order_items
  - RLS: Enabled on all tables
*/

-- 1. Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  price numeric NOT NULL,
  image_url text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Products are viewable by everyone" 
  ON public.products FOR SELECT 
  USING (true);

-- 2. Cart Items Table
CREATE TABLE IF NOT EXISTS public.cart_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  product_id bigint REFERENCES public.products NOT NULL,
  quantity integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, product_id)
);

ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own cart" 
  ON public.cart_items FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert into their own cart" 
  ON public.cart_items FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own cart" 
  ON public.cart_items FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own cart" 
  ON public.cart_items FOR DELETE 
  USING (auth.uid() = user_id);

-- 3. Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  total_amount numeric NOT NULL,
  status text DEFAULT 'pending', -- pending, paid, shipped
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own orders" 
  ON public.orders FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create orders" 
  ON public.orders FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

-- 4. Order Items Table
CREATE TABLE IF NOT EXISTS public.order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint REFERENCES public.orders NOT NULL,
  product_id bigint REFERENCES public.products NOT NULL,
  quantity integer NOT NULL,
  price_at_purchase numeric NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own order items" 
  ON public.order_items FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM public.orders 
      WHERE orders.id = order_items.order_id 
      AND orders.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can create order items" 
  ON public.order_items FOR INSERT 
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.orders 
      WHERE orders.id = order_items.order_id 
      AND orders.user_id = auth.uid()
    )
  );

-- 5. Seed Data
INSERT INTO public.products (title, description, price, image_url) VALUES
  ('Herman Miller Aeron Chair', 'The benchmark for ergonomic seating. Remastered design with 8Z Pellicle suspension and fully adjustable arms.', 1495.00, 'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&q=80&w=800'),
  ('Keychron Q1 Pro Mechanical Keyboard', 'Premium custom wireless mechanical keyboard with QMK/VIA support and a full aluminum body.', 199.00, 'https://images.unsplash.com/photo-1587829741301-dc798b91a603?auto=format&fit=crop&q=80&w=800'),
  ('Sony WH-1000XM5 Headphones', 'Industry-leading noise cancellation with two processors controlling eight microphones for unprecedented silence.', 398.00, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=800'),
  ('Apple Watch Ultra 2', 'The most rugged and capable Apple Watch. Designed for outdoor adventures and endurance training.', 799.00, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800'),
  ('BenQ ScreenBar Halo', 'Intelligent monitor light bar with wireless controller and back light for immersive eye care.', 179.00, 'https://images.unsplash.com/photo-1507473888900-52e1adad5474?auto=format&fit=crop&q=80&w=800'),
  ('Dell UltraSharp 32 6K Monitor', 'Experience exceptional details and color accuracy with 6K resolution and IPS Black technology.', 2450.00, 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=800'),
  ('Bellroy Laptop Sleeve', 'Slim, protective sleeve with magnetic entry. Woven from recycled fabrics and environmentally certified leather.', 55.00, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800'),
  ('Logitech MX Master 3S', 'An icon remastered. Quiet clicks and 8K DPI track-on-glass sensor for ultimate precision.', 99.00, 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800'),
  ('Ember Temperature Control Mug', 'Keep your drink at the perfect temperature from the first sip to the last. Controlled via smartphone.', 129.00, 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&q=80&w=800'),
  ('Samsung T7 Shield 2TB', 'Rugged durability with IP65 rating for water and dust resistance. Blazing fast transfer speeds.', 169.00, 'https://images.unsplash.com/photo-1597872252165-4827c2bdb042?auto=format&fit=crop&q=80&w=800'),
  ('Grovemade Wool Felt Desk Mat', 'Premium merino wool felt adds warmth and organization to your workspace while protecting your desk.', 120.00, 'https://images.unsplash.com/photo-1616488585517-75d713403e38?auto=format&fit=crop&q=80&w=800'),
  ('Blue Yeti X Microphone', 'Professional USB microphone for gaming, streaming, and podcasting with Blue VO!CE effects.', 169.99, 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&q=80&w=800'),
  ('Twelve South Curve Stand', 'Elegant aluminum stand that elevates your MacBook for better ergonomics and airflow.', 59.99, 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&q=80&w=800'),
  ('Sonos Era 100 Speaker', 'Next-gen acoustics and new levels of connectivity. Stereo sound from a single compact speaker.', 249.00, 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&q=80&w=800'),
  ('Fujifilm X100V Digital Camera', 'The ultimate street photography camera. 26.1MP sensor, 4K video, and classic dial-based controls.', 1399.00, 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800');
